-- FlexQL smoke script (run with flexql-client --file or paste into REPL)
CREATE TABLE IF NOT EXISTS SMOKE(ID DECIMAL PRIMARY KEY, NAME VARCHAR(32), EXPIRES_AT DECIMAL);
INSERT INTO SMOKE VALUES (1, 'ok', 0);
SELECT * FROM SMOKE WHERE ID = 1;
SELECT NAME FROM SMOKE WHERE ID >= 1;
-- .quit
